#!/bin/bash
#
# BUILD THE ISO!!!
# this builds the GoOSe releases, 
# based upon the process described below.
# 

# Repositories must be mashed and available in a repository
# Also, must have mock installed along with the pungi-goose.ks

MOCK=/usr/bin/mock
KS=/mnt/koji/releng/pungi-goose.ks
KS_MOCK_PATH=/root
PUNGI=/usr/bin/pungi

ISO_NAME=GoOSe
ISO_FLAVOR=Linux
ISO_DEST=/root/gl6
ISO_CACHEDIR=/root/gl6/cache/
ISO_KS=pungi-goose.ks
ISO_VERSION=6

for ARCH in x86_64 i386; do  
  ${MOCK} -r goose-6-${ARCH} --init
  ${MOCK} -r goose-6-${ARCH} --install pungi
  ${MOCK} -r goose-6-${ARCH} --copyin ${KS} ${KS_MOCK_PATH}
  ${MOCK} -r goose-6-${ARCH} --chroot  '${PUNGI} --name=${ISO_NAME} --flavor=${ISO_FLAVOR} --destdir=${ISO_DEST} --cachedir=ISO_CACHEDIR --all-stages -c ${KS_MOCK_PATH}/${ISO_KS}  --ver=${ISO_VERSION} --force'
done
